### PR TITLE
Update landing site

### PR DESCRIPTION
**Pull request by nathanbegbie**
This PR does a few things:
- Makes the site responsive (works on mobile and desktop)
- Adds in links to activity (on d-portal)
- Adds in links to organization (on d-portal)
- Add in links in nav bar to docs, project and code
- removes example

### CODE REVIEW

**Comment by nathanbegbie** [comment]
Kapture 2020-01-28 at 13 04 16

**Comment by Rabshab** [comment]
Just realised that you removed the little tag line. I wonder if the intent of the site is a bit less clear without it.

**Comment by nathanbegbie** [comment]
> Woah ho. Very slick 💅
> 
> Might be better to make the content area fill the viewport, to get rid of the (now empty) whitespace underneath. But this is definitely a big improvement 👍

I did try to fill out the whitespace, but ran into a number of issues - keeping the image introduced some interesting issues that I don't have time to deal with 😬

> Just realised that you removed the little tag line. I wonder if the intent of the site is a bit less clear without it.

Ah! I'll see if I can fit it back in

**Comment by nathanbegbie** [comment]
Screenshot 2020-01-28 at 14 26 20

**Comment by nathanbegbie** [comment]
Screenshot 2020-01-28 at 14 26 35

**Comment by nathanbegbie** [comment]
Updated to include the tag line

**Pull request merged**
